# wrangler.toml
name = "gemini-code-api"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gemini-code"
database_id = "ad7cb701-d03f-48de-9dc6-63998a0bcc66"
